# Generated by Django 4.2.3 on 2023-07-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_kor', models.TextField(default='')),
                ('title_eng', models.TextField(default='')),
                ('poster_url', models.URLField(max_length=1024)),
                ('rating_aud', models.TextField(default='')),
                ('rating_cri', models.TextField(default='')),
                ('rating_net', models.TextField(default='')),
                ('genre', models.TextField(default='')),
                ('showtimes', models.TextField(default='')),
                ('release_date', models.TextField(default='')),
                ('rate', models.CharField(max_length=20)),
                ('summary', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=30)),
                ('image_url', models.URLField(max_length=1024)),
            ],
        ),
    ]
