# Generated by Django 4.2.3 on 2023-07-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='staff',
            field=models.ManyToManyField(to='movie.staff'),
        ),
    ]
