# Generated by Django 4.2.3 on 2023-07-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='staff',
        ),
        migrations.AddField(
            model_name='staff',
            name='movies',
            field=models.ManyToManyField(related_name='staffs', to='movie.movie'),
        ),
    ]
