# Generated by Django 4.2.3 on 2023-07-14 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_remove_movie_staff_staff_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='movies',
        ),
        migrations.AddField(
            model_name='staff',
            name='movies',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='movie.movie'),
        ),
    ]
