# Generated by Django 4.2.3 on 2023-07-14 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_remove_staff_movies_staff_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='movies',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='movie.movie'),
        ),
    ]
