# Generated by Django 4.2.3 on 2023-07-14 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_alter_staff_movies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='movies',
            new_name='movie_title',
        ),
    ]
